# Generated by Django 5.2.5 on 2026-01-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_amount',
            new_name='passengers',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_passengers',
            new_name='total_fare',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fare',
        ),
    ]
