# Generated by Django 6.0 on 2026-02-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_total_amount_booking_passengers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='passengers',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_fare',
            new_name='total_passengers',
        ),
    ]
