# Generated by Django 5.2.5 on 2026-02-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_passengers_booking_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='journey_type',
            field=models.CharField(choices=[('ONWARD', 'Onward'), ('RETURN', 'Return')], default='ONWARD', max_length=10),
        ),
    ]
